# Generated by Django 5.1.6 on 2025-02-20 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlabs', '0002_alter_testimonials_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(default=datetime.datetime(2025, 2, 20, 10, 6, 32, 305103, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
