# Generated by Django 5.1.6 on 2025-02-21 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlabs', '0005_post_short_detail_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 21, 4, 43, 35, 640326, tzinfo=datetime.timezone.utc)),
        ),
    ]
