# Generated by Django 5.1.6 on 2025-02-23 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlabs', '0009_postcomments_created_at_postcomments_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='author_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=320),
            preserve_default=False,
        ),
    ]
