# Generated by Django 5.1.6 on 2025-02-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlabs', '0010_postcomments_author_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='airlabs_blog',
        ),
        migrations.AlterModelTable(
            name='post',
            table='airlabs_post',
        ),
        migrations.AlterModelTable(
            name='postauthor',
            table='airlabs_post_author',
        ),
        migrations.AlterModelTable(
            name='postcategory',
            table='airlabs_post_category',
        ),
        migrations.AlterModelTable(
            name='postcomments',
            table='airlabs_post_comments',
        ),
        migrations.AlterModelTable(
            name='testimonials',
            table='airlabs_testimonials',
        ),
    ]
