# Generated by Django 5.1.6 on 2025-02-20 23:08

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_blog_postauthor_postcategory_post_postcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 20, 23, 7, 25, 511475, tzinfo=datetime.timezone.utc)),
        ),
    ]
